// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.19.1
// source: pkg/device/evcharger/evcharger.proto

package evcharger

import (
	traits "github.com/smart-core-os/sc-api/go/traits"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PlugInEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Full describes the values the plugged in device would have when full.
	//
	// Example
	//
	//    Percentage: 100, // when full, the ev is at 100%
	//    DistanceKm: 300, // when full, the ev can travel 300 km
	//    EnergyKwh:  100, // when full, the ev hold 100 kWh of energy
	Full *traits.EnergyLevel_Quantity `protobuf:"bytes,1,opt,name=full,proto3" json:"full,omitempty"`
	// Level encodes the current charge level when the vehicle was plugged in.
	Level *traits.EnergyLevel_Quantity `protobuf:"bytes,2,opt,name=level,proto3" json:"level,omitempty"`
	// Supported charging modes of the device that was just plugged in.
	// Empty implies the charger can make the decision.
	// The first mode is the preferred mode and will be marked as the Normal mode.
	Modes []*PlugInEvent_ChargeMode `protobuf:"bytes,3,rep,name=modes,proto3" json:"modes,omitempty"`
}

func (x *PlugInEvent) Reset() {
	*x = PlugInEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_device_evcharger_evcharger_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PlugInEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlugInEvent) ProtoMessage() {}

func (x *PlugInEvent) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_device_evcharger_evcharger_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlugInEvent.ProtoReflect.Descriptor instead.
func (*PlugInEvent) Descriptor() ([]byte, []int) {
	return file_pkg_device_evcharger_evcharger_proto_rawDescGZIP(), []int{0}
}

func (x *PlugInEvent) GetFull() *traits.EnergyLevel_Quantity {
	if x != nil {
		return x.Full
	}
	return nil
}

func (x *PlugInEvent) GetLevel() *traits.EnergyLevel_Quantity {
	if x != nil {
		return x.Level
	}
	return nil
}

func (x *PlugInEvent) GetModes() []*PlugInEvent_ChargeMode {
	if x != nil {
		return x.Modes
	}
	return nil
}

type PlugInRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name  string       `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Event *PlugInEvent `protobuf:"bytes,2,opt,name=event,proto3" json:"event,omitempty"`
}

func (x *PlugInRequest) Reset() {
	*x = PlugInRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_device_evcharger_evcharger_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PlugInRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlugInRequest) ProtoMessage() {}

func (x *PlugInRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_device_evcharger_evcharger_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlugInRequest.ProtoReflect.Descriptor instead.
func (*PlugInRequest) Descriptor() ([]byte, []int) {
	return file_pkg_device_evcharger_evcharger_proto_rawDescGZIP(), []int{1}
}

func (x *PlugInRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PlugInRequest) GetEvent() *PlugInEvent {
	if x != nil {
		return x.Event
	}
	return nil
}

type PlugInResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *PlugInResponse) Reset() {
	*x = PlugInResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_device_evcharger_evcharger_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PlugInResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlugInResponse) ProtoMessage() {}

func (x *PlugInResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_device_evcharger_evcharger_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlugInResponse.ProtoReflect.Descriptor instead.
func (*PlugInResponse) Descriptor() ([]byte, []int) {
	return file_pkg_device_evcharger_evcharger_proto_rawDescGZIP(), []int{2}
}

type ChargeStartRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *ChargeStartRequest) Reset() {
	*x = ChargeStartRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_device_evcharger_evcharger_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChargeStartRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChargeStartRequest) ProtoMessage() {}

func (x *ChargeStartRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_device_evcharger_evcharger_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChargeStartRequest.ProtoReflect.Descriptor instead.
func (*ChargeStartRequest) Descriptor() ([]byte, []int) {
	return file_pkg_device_evcharger_evcharger_proto_rawDescGZIP(), []int{3}
}

func (x *ChargeStartRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ChargeStartResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ChargeStartResponse) Reset() {
	*x = ChargeStartResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_device_evcharger_evcharger_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChargeStartResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChargeStartResponse) ProtoMessage() {}

func (x *ChargeStartResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_device_evcharger_evcharger_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChargeStartResponse.ProtoReflect.Descriptor instead.
func (*ChargeStartResponse) Descriptor() ([]byte, []int) {
	return file_pkg_device_evcharger_evcharger_proto_rawDescGZIP(), []int{4}
}

type UnplugRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *UnplugRequest) Reset() {
	*x = UnplugRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_device_evcharger_evcharger_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UnplugRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnplugRequest) ProtoMessage() {}

func (x *UnplugRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_device_evcharger_evcharger_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnplugRequest.ProtoReflect.Descriptor instead.
func (*UnplugRequest) Descriptor() ([]byte, []int) {
	return file_pkg_device_evcharger_evcharger_proto_rawDescGZIP(), []int{5}
}

func (x *UnplugRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type UnplugResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UnplugResponse) Reset() {
	*x = UnplugResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_device_evcharger_evcharger_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UnplugResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnplugResponse) ProtoMessage() {}

func (x *UnplugResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_device_evcharger_evcharger_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnplugResponse.ProtoReflect.Descriptor instead.
func (*UnplugResponse) Descriptor() ([]byte, []int) {
	return file_pkg_device_evcharger_evcharger_proto_rawDescGZIP(), []int{6}
}

type PlugInEvent_ChargeMode struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          string                         `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title       string                         `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description string                         `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Segments    []*traits.ElectricMode_Segment `protobuf:"bytes,4,rep,name=segments,proto3" json:"segments,omitempty"`
}

func (x *PlugInEvent_ChargeMode) Reset() {
	*x = PlugInEvent_ChargeMode{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_device_evcharger_evcharger_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PlugInEvent_ChargeMode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlugInEvent_ChargeMode) ProtoMessage() {}

func (x *PlugInEvent_ChargeMode) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_device_evcharger_evcharger_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlugInEvent_ChargeMode.ProtoReflect.Descriptor instead.
func (*PlugInEvent_ChargeMode) Descriptor() ([]byte, []int) {
	return file_pkg_device_evcharger_evcharger_proto_rawDescGZIP(), []int{0, 0}
}

func (x *PlugInEvent_ChargeMode) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PlugInEvent_ChargeMode) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *PlugInEvent_ChargeMode) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *PlugInEvent_ChargeMode) GetSegments() []*traits.ElectricMode_Segment {
	if x != nil {
		return x.Segments
	}
	return nil
}

var File_pkg_device_evcharger_evcharger_proto protoreflect.FileDescriptor

var file_pkg_device_evcharger_evcharger_proto_rawDesc = []byte{
	0x0a, 0x24, 0x70, 0x6b, 0x67, 0x2f, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x65, 0x76, 0x63,
	0x68, 0x61, 0x72, 0x67, 0x65, 0x72, 0x2f, 0x65, 0x76, 0x63, 0x68, 0x61, 0x72, 0x67, 0x65, 0x72,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x25, 0x73, 0x6d, 0x61, 0x72, 0x74, 0x63, 0x6f, 0x72,
	0x65, 0x2e, 0x70, 0x6c, 0x61, 0x79, 0x67, 0x72, 0x6f, 0x75, 0x6e, 0x64, 0x2e, 0x64, 0x65, 0x76,
	0x69, 0x63, 0x65, 0x2e, 0x65, 0x76, 0x63, 0x68, 0x61, 0x72, 0x67, 0x65, 0x72, 0x1a, 0x15, 0x74,
	0x72, 0x61, 0x69, 0x74, 0x73, 0x2f, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x72, 0x69, 0x63, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1b, 0x74, 0x72, 0x61, 0x69, 0x74, 0x73, 0x2f, 0x65, 0x6e, 0x65,
	0x72, 0x67, 0x79, 0x5f, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0xf7, 0x02, 0x0a, 0x0b, 0x50, 0x6c, 0x75, 0x67, 0x49, 0x6e, 0x45, 0x76, 0x65, 0x6e,
	0x74, 0x12, 0x3a, 0x0a, 0x04, 0x66, 0x75, 0x6c, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x26, 0x2e, 0x73, 0x6d, 0x61, 0x72, 0x74, 0x63, 0x6f, 0x72, 0x65, 0x2e, 0x74, 0x72, 0x61, 0x69,
	0x74, 0x73, 0x2e, 0x45, 0x6e, 0x65, 0x72, 0x67, 0x79, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x2e, 0x51,
	0x75, 0x61, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x52, 0x04, 0x66, 0x75, 0x6c, 0x6c, 0x12, 0x3c, 0x0a,
	0x05, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x26, 0x2e, 0x73,
	0x6d, 0x61, 0x72, 0x74, 0x63, 0x6f, 0x72, 0x65, 0x2e, 0x74, 0x72, 0x61, 0x69, 0x74, 0x73, 0x2e,
	0x45, 0x6e, 0x65, 0x72, 0x67, 0x79, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x2e, 0x51, 0x75, 0x61, 0x6e,
	0x74, 0x69, 0x74, 0x79, 0x52, 0x05, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x12, 0x53, 0x0a, 0x05, 0x6d,
	0x6f, 0x64, 0x65, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x3d, 0x2e, 0x73, 0x6d, 0x61,
	0x72, 0x74, 0x63, 0x6f, 0x72, 0x65, 0x2e, 0x70, 0x6c, 0x61, 0x79, 0x67, 0x72, 0x6f, 0x75, 0x6e,
	0x64, 0x2e, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x65, 0x76, 0x63, 0x68, 0x61, 0x72, 0x67,
	0x65, 0x72, 0x2e, 0x50, 0x6c, 0x75, 0x67, 0x49, 0x6e, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x2e, 0x43,
	0x68, 0x61, 0x72, 0x67, 0x65, 0x4d, 0x6f, 0x64, 0x65, 0x52, 0x05, 0x6d, 0x6f, 0x64, 0x65, 0x73,
	0x1a, 0x98, 0x01, 0x0a, 0x0a, 0x43, 0x68, 0x61, 0x72, 0x67, 0x65, 0x4d, 0x6f, 0x64, 0x65, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12,
	0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70,
	0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63,
	0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x42, 0x0a, 0x08, 0x73, 0x65, 0x67, 0x6d, 0x65,
	0x6e, 0x74, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x26, 0x2e, 0x73, 0x6d, 0x61, 0x72,
	0x74, 0x63, 0x6f, 0x72, 0x65, 0x2e, 0x74, 0x72, 0x61, 0x69, 0x74, 0x73, 0x2e, 0x45, 0x6c, 0x65,
	0x63, 0x74, 0x72, 0x69, 0x63, 0x4d, 0x6f, 0x64, 0x65, 0x2e, 0x53, 0x65, 0x67, 0x6d, 0x65, 0x6e,
	0x74, 0x52, 0x08, 0x73, 0x65, 0x67, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x22, 0x6d, 0x0a, 0x0d, 0x50,
	0x6c, 0x75, 0x67, 0x49, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x12, 0x48, 0x0a, 0x05, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x32, 0x2e, 0x73, 0x6d, 0x61, 0x72, 0x74, 0x63, 0x6f, 0x72, 0x65, 0x2e, 0x70, 0x6c, 0x61, 0x79,
	0x67, 0x72, 0x6f, 0x75, 0x6e, 0x64, 0x2e, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x65, 0x76,
	0x63, 0x68, 0x61, 0x72, 0x67, 0x65, 0x72, 0x2e, 0x50, 0x6c, 0x75, 0x67, 0x49, 0x6e, 0x45, 0x76,
	0x65, 0x6e, 0x74, 0x52, 0x05, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x22, 0x10, 0x0a, 0x0e, 0x50, 0x6c,
	0x75, 0x67, 0x49, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x28, 0x0a, 0x12,
	0x43, 0x68, 0x61, 0x72, 0x67, 0x65, 0x53, 0x74, 0x61, 0x72, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x15, 0x0a, 0x13, 0x43, 0x68, 0x61, 0x72, 0x67, 0x65,
	0x53, 0x74, 0x61, 0x72, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x23, 0x0a,
	0x0d, 0x55, 0x6e, 0x70, 0x6c, 0x75, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12,
	0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x22, 0x10, 0x0a, 0x0e, 0x55, 0x6e, 0x70, 0x6c, 0x75, 0x67, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x32, 0x83, 0x03, 0x0a, 0x0c, 0x45, 0x56, 0x43, 0x68, 0x61, 0x72, 0x67,
	0x65, 0x72, 0x41, 0x70, 0x69, 0x12, 0x75, 0x0a, 0x06, 0x50, 0x6c, 0x75, 0x67, 0x49, 0x6e, 0x12,
	0x34, 0x2e, 0x73, 0x6d, 0x61, 0x72, 0x74, 0x63, 0x6f, 0x72, 0x65, 0x2e, 0x70, 0x6c, 0x61, 0x79,
	0x67, 0x72, 0x6f, 0x75, 0x6e, 0x64, 0x2e, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x65, 0x76,
	0x63, 0x68, 0x61, 0x72, 0x67, 0x65, 0x72, 0x2e, 0x50, 0x6c, 0x75, 0x67, 0x49, 0x6e, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x35, 0x2e, 0x73, 0x6d, 0x61, 0x72, 0x74, 0x63, 0x6f, 0x72,
	0x65, 0x2e, 0x70, 0x6c, 0x61, 0x79, 0x67, 0x72, 0x6f, 0x75, 0x6e, 0x64, 0x2e, 0x64, 0x65, 0x76,
	0x69, 0x63, 0x65, 0x2e, 0x65, 0x76, 0x63, 0x68, 0x61, 0x72, 0x67, 0x65, 0x72, 0x2e, 0x50, 0x6c,
	0x75, 0x67, 0x49, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x84, 0x01, 0x0a,
	0x0b, 0x43, 0x68, 0x61, 0x72, 0x67, 0x65, 0x53, 0x74, 0x61, 0x72, 0x74, 0x12, 0x39, 0x2e, 0x73,
	0x6d, 0x61, 0x72, 0x74, 0x63, 0x6f, 0x72, 0x65, 0x2e, 0x70, 0x6c, 0x61, 0x79, 0x67, 0x72, 0x6f,
	0x75, 0x6e, 0x64, 0x2e, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x65, 0x76, 0x63, 0x68, 0x61,
	0x72, 0x67, 0x65, 0x72, 0x2e, 0x43, 0x68, 0x61, 0x72, 0x67, 0x65, 0x53, 0x74, 0x61, 0x72, 0x74,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x3a, 0x2e, 0x73, 0x6d, 0x61, 0x72, 0x74, 0x63,
	0x6f, 0x72, 0x65, 0x2e, 0x70, 0x6c, 0x61, 0x79, 0x67, 0x72, 0x6f, 0x75, 0x6e, 0x64, 0x2e, 0x64,
	0x65, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x65, 0x76, 0x63, 0x68, 0x61, 0x72, 0x67, 0x65, 0x72, 0x2e,
	0x43, 0x68, 0x61, 0x72, 0x67, 0x65, 0x53, 0x74, 0x61, 0x72, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x75, 0x0a, 0x06, 0x55, 0x6e, 0x70, 0x6c, 0x75, 0x67, 0x12, 0x34, 0x2e,
	0x73, 0x6d, 0x61, 0x72, 0x74, 0x63, 0x6f, 0x72, 0x65, 0x2e, 0x70, 0x6c, 0x61, 0x79, 0x67, 0x72,
	0x6f, 0x75, 0x6e, 0x64, 0x2e, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x65, 0x76, 0x63, 0x68,
	0x61, 0x72, 0x67, 0x65, 0x72, 0x2e, 0x55, 0x6e, 0x70, 0x6c, 0x75, 0x67, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x35, 0x2e, 0x73, 0x6d, 0x61, 0x72, 0x74, 0x63, 0x6f, 0x72, 0x65, 0x2e,
	0x70, 0x6c, 0x61, 0x79, 0x67, 0x72, 0x6f, 0x75, 0x6e, 0x64, 0x2e, 0x64, 0x65, 0x76, 0x69, 0x63,
	0x65, 0x2e, 0x65, 0x76, 0x63, 0x68, 0x61, 0x72, 0x67, 0x65, 0x72, 0x2e, 0x55, 0x6e, 0x70, 0x6c,
	0x75, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x3d, 0x5a, 0x3b, 0x67, 0x69,
	0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x73, 0x6d, 0x61, 0x72, 0x74, 0x2d, 0x63,
	0x6f, 0x72, 0x65, 0x2d, 0x6f, 0x73, 0x2f, 0x73, 0x63, 0x2d, 0x70, 0x6c, 0x61, 0x79, 0x67, 0x72,
	0x6f, 0x75, 0x6e, 0x64, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x2f,
	0x65, 0x76, 0x63, 0x68, 0x61, 0x72, 0x67, 0x65, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_pkg_device_evcharger_evcharger_proto_rawDescOnce sync.Once
	file_pkg_device_evcharger_evcharger_proto_rawDescData = file_pkg_device_evcharger_evcharger_proto_rawDesc
)

func file_pkg_device_evcharger_evcharger_proto_rawDescGZIP() []byte {
	file_pkg_device_evcharger_evcharger_proto_rawDescOnce.Do(func() {
		file_pkg_device_evcharger_evcharger_proto_rawDescData = protoimpl.X.CompressGZIP(file_pkg_device_evcharger_evcharger_proto_rawDescData)
	})
	return file_pkg_device_evcharger_evcharger_proto_rawDescData
}

var file_pkg_device_evcharger_evcharger_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_pkg_device_evcharger_evcharger_proto_goTypes = []interface{}{
	(*PlugInEvent)(nil),                 // 0: smartcore.playground.device.evcharger.PlugInEvent
	(*PlugInRequest)(nil),               // 1: smartcore.playground.device.evcharger.PlugInRequest
	(*PlugInResponse)(nil),              // 2: smartcore.playground.device.evcharger.PlugInResponse
	(*ChargeStartRequest)(nil),          // 3: smartcore.playground.device.evcharger.ChargeStartRequest
	(*ChargeStartResponse)(nil),         // 4: smartcore.playground.device.evcharger.ChargeStartResponse
	(*UnplugRequest)(nil),               // 5: smartcore.playground.device.evcharger.UnplugRequest
	(*UnplugResponse)(nil),              // 6: smartcore.playground.device.evcharger.UnplugResponse
	(*PlugInEvent_ChargeMode)(nil),      // 7: smartcore.playground.device.evcharger.PlugInEvent.ChargeMode
	(*traits.EnergyLevel_Quantity)(nil), // 8: smartcore.traits.EnergyLevel.Quantity
	(*traits.ElectricMode_Segment)(nil), // 9: smartcore.traits.ElectricMode.Segment
}
var file_pkg_device_evcharger_evcharger_proto_depIdxs = []int32{
	8, // 0: smartcore.playground.device.evcharger.PlugInEvent.full:type_name -> smartcore.traits.EnergyLevel.Quantity
	8, // 1: smartcore.playground.device.evcharger.PlugInEvent.level:type_name -> smartcore.traits.EnergyLevel.Quantity
	7, // 2: smartcore.playground.device.evcharger.PlugInEvent.modes:type_name -> smartcore.playground.device.evcharger.PlugInEvent.ChargeMode
	0, // 3: smartcore.playground.device.evcharger.PlugInRequest.event:type_name -> smartcore.playground.device.evcharger.PlugInEvent
	9, // 4: smartcore.playground.device.evcharger.PlugInEvent.ChargeMode.segments:type_name -> smartcore.traits.ElectricMode.Segment
	1, // 5: smartcore.playground.device.evcharger.EVChargerApi.PlugIn:input_type -> smartcore.playground.device.evcharger.PlugInRequest
	3, // 6: smartcore.playground.device.evcharger.EVChargerApi.ChargeStart:input_type -> smartcore.playground.device.evcharger.ChargeStartRequest
	5, // 7: smartcore.playground.device.evcharger.EVChargerApi.Unplug:input_type -> smartcore.playground.device.evcharger.UnplugRequest
	2, // 8: smartcore.playground.device.evcharger.EVChargerApi.PlugIn:output_type -> smartcore.playground.device.evcharger.PlugInResponse
	4, // 9: smartcore.playground.device.evcharger.EVChargerApi.ChargeStart:output_type -> smartcore.playground.device.evcharger.ChargeStartResponse
	6, // 10: smartcore.playground.device.evcharger.EVChargerApi.Unplug:output_type -> smartcore.playground.device.evcharger.UnplugResponse
	8, // [8:11] is the sub-list for method output_type
	5, // [5:8] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_pkg_device_evcharger_evcharger_proto_init() }
func file_pkg_device_evcharger_evcharger_proto_init() {
	if File_pkg_device_evcharger_evcharger_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pkg_device_evcharger_evcharger_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PlugInEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_device_evcharger_evcharger_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PlugInRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_device_evcharger_evcharger_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PlugInResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_device_evcharger_evcharger_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChargeStartRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_device_evcharger_evcharger_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChargeStartResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_device_evcharger_evcharger_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UnplugRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_device_evcharger_evcharger_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UnplugResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_device_evcharger_evcharger_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PlugInEvent_ChargeMode); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pkg_device_evcharger_evcharger_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_device_evcharger_evcharger_proto_goTypes,
		DependencyIndexes: file_pkg_device_evcharger_evcharger_proto_depIdxs,
		MessageInfos:      file_pkg_device_evcharger_evcharger_proto_msgTypes,
	}.Build()
	File_pkg_device_evcharger_evcharger_proto = out.File
	file_pkg_device_evcharger_evcharger_proto_rawDesc = nil
	file_pkg_device_evcharger_evcharger_proto_goTypes = nil
	file_pkg_device_evcharger_evcharger_proto_depIdxs = nil
}
