# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com
before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy
builds:
  - goos:
      - linux
      - windows
      - darwin
archives:
  - format_overrides:
      - goos: windows
        format: zip
snapshot:
  name_template: '{{ incpatch .Version }}-next'
release:
  # if the tag has a suffix (v1.0.0-beta), mark as prerelease
  prerelease: auto
  footer: |
    **Full Changelog**: https://github.com/smart-core-os/sc-playground/compare/{{ .PreviousTag }}...{{ .Tag }}
changelog:
  sort: asc
  groups:
    - title: ':tada: New Features'
      regexp: "^.*feat[(\\w)]*:+.*$"
      order: 0
    - title: ':hammer: Bug Fixes'
      regexp: "^.*fix[(\\w)]*:+.*$"
      order: 1
    - title: 'Other changes'
      order: 999
  filters:
    exclude:
      - '^test:'
      - '^typo:'
      - '^chore'
