package metadata

import (
	"log"

	"github.com/smart-core-os/sc-api/go/traits"
	"github.com/smart-core-os/sc-golang/pkg/resource"
	"github.com/smart-core-os/sc-golang/pkg/router"
	"github.com/smart-core-os/sc-golang/pkg/trait"
	"github.com/smart-core-os/sc-golang/pkg/trait/metadata"
	"github.com/smart-core-os/sc-playground/pkg/node"
)

func Activate(n *node.Node) {
	r := metadata.NewApiRouter(
		metadata.WithMetadataApiClientFactory(func(name string) (traits.MetadataApiClient, error) {
			model := metadata.NewModel(resource.WithInitialValue(autoGeneratedDeviceMetadata(name)))
			return metadata.WrapApi(metadata.NewModelServer(model)), nil
		}),
		router.WithOnCommit(func(name string, client interface{}) {
			log.Printf("MetadataApiClient(%v) auto-created", name)
			n.Announce(name, node.HasTrait(trait.Metadata, node.NoAddMetadata()))
		}),
	)
	n.AddRouter(r)
}

func autoGeneratedDeviceMetadata(name string) *traits.Metadata {
	return &traits.Metadata{
		Name: name,
		Appearance: &traits.Metadata_Appearance{
			Description: "Auto-generated device",
		},
		Traits: []*traits.TraitMetadata{
			{Name: string(trait.Metadata), More: node.AutoTraitMetadata},
		},
	}
}
