// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package playpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// PlaygroundApiClient is the client API for PlaygroundApi service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PlaygroundApiClient interface {
	AddDeviceTrait(ctx context.Context, in *AddDeviceTraitRequest, opts ...grpc.CallOption) (*AddDeviceTraitResponse, error)
	ListSupportedTraits(ctx context.Context, in *ListSupportedTraitsRequest, opts ...grpc.CallOption) (*ListSupportedTraitsResponse, error)
}

type playgroundApiClient struct {
	cc grpc.ClientConnInterface
}

func NewPlaygroundApiClient(cc grpc.ClientConnInterface) PlaygroundApiClient {
	return &playgroundApiClient{cc}
}

func (c *playgroundApiClient) AddDeviceTrait(ctx context.Context, in *AddDeviceTraitRequest, opts ...grpc.CallOption) (*AddDeviceTraitResponse, error) {
	out := new(AddDeviceTraitResponse)
	err := c.cc.Invoke(ctx, "/smartcore.playground.api.PlaygroundApi/AddDeviceTrait", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *playgroundApiClient) ListSupportedTraits(ctx context.Context, in *ListSupportedTraitsRequest, opts ...grpc.CallOption) (*ListSupportedTraitsResponse, error) {
	out := new(ListSupportedTraitsResponse)
	err := c.cc.Invoke(ctx, "/smartcore.playground.api.PlaygroundApi/ListSupportedTraits", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PlaygroundApiServer is the server API for PlaygroundApi service.
// All implementations must embed UnimplementedPlaygroundApiServer
// for forward compatibility
type PlaygroundApiServer interface {
	AddDeviceTrait(context.Context, *AddDeviceTraitRequest) (*AddDeviceTraitResponse, error)
	ListSupportedTraits(context.Context, *ListSupportedTraitsRequest) (*ListSupportedTraitsResponse, error)
	mustEmbedUnimplementedPlaygroundApiServer()
}

// UnimplementedPlaygroundApiServer must be embedded to have forward compatible implementations.
type UnimplementedPlaygroundApiServer struct {
}

func (UnimplementedPlaygroundApiServer) AddDeviceTrait(context.Context, *AddDeviceTraitRequest) (*AddDeviceTraitResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddDeviceTrait not implemented")
}
func (UnimplementedPlaygroundApiServer) ListSupportedTraits(context.Context, *ListSupportedTraitsRequest) (*ListSupportedTraitsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListSupportedTraits not implemented")
}
func (UnimplementedPlaygroundApiServer) mustEmbedUnimplementedPlaygroundApiServer() {}

// UnsafePlaygroundApiServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PlaygroundApiServer will
// result in compilation errors.
type UnsafePlaygroundApiServer interface {
	mustEmbedUnimplementedPlaygroundApiServer()
}

func RegisterPlaygroundApiServer(s grpc.ServiceRegistrar, srv PlaygroundApiServer) {
	s.RegisterService(&PlaygroundApi_ServiceDesc, srv)
}

func _PlaygroundApi_AddDeviceTrait_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddDeviceTraitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlaygroundApiServer).AddDeviceTrait(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/smartcore.playground.api.PlaygroundApi/AddDeviceTrait",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlaygroundApiServer).AddDeviceTrait(ctx, req.(*AddDeviceTraitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlaygroundApi_ListSupportedTraits_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSupportedTraitsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlaygroundApiServer).ListSupportedTraits(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/smartcore.playground.api.PlaygroundApi/ListSupportedTraits",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlaygroundApiServer).ListSupportedTraits(ctx, req.(*ListSupportedTraitsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PlaygroundApi_ServiceDesc is the grpc.ServiceDesc for PlaygroundApi service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PlaygroundApi_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "smartcore.playground.api.PlaygroundApi",
	HandlerType: (*PlaygroundApiServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddDeviceTrait",
			Handler:    _PlaygroundApi_AddDeviceTrait_Handler,
		},
		{
			MethodName: "ListSupportedTraits",
			Handler:    _PlaygroundApi_ListSupportedTraits_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/playpb/playground.proto",
}
