name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GOPRIVATE: github.com/smart-core-os/*
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: 1.17.x
      - uses: actions/checkout@v2
      - name: Private repo auth
        run: git config --global url."https://${{ secrets.GO_MOD_TOKEN }}:x-oauth-basic@github.com/smart-core-os".insteadOf "https://github.com/smart-core-os"
      - name: go:embed setup
        # Needed so `//go:embed ./dist` doesn't fail when compiled - because we don't `yarn build` and ./dist isn't in vcs
        run: mkdir -p ui/playground/dist && touch ui/playground/dist/embedkeep
      - name: Test
        run: go test ./...
