name: release

on:
  push:
    branches: [ main ]
    tags:
      - "v*" # Push events to matching v*, i.e. v1.0, v20.15.10

# $GITHUB_REF_NAME - https://docs.github.com/en/actions/learn-github-actions/environment-variables#default-environment-variables

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # Build the playground ui
      - uses: actions/setup-node@v2
        with:
          cache: yarn
          cache-dependency-path: ui/**/yarn.lock
      - name: Nexus Auth
        run: |
          npm config set always-auth true
          npm login --registry https://nexus.vanti.co.uk/repository/npm-public --scope=@smart-core-os -e matt.nathan@vanti.co.uk << EOF
          ${{ secrets.NEXUS_USER }}
          ${{ secrets.NEXUS_PASS }}
          ${{ secrets.NEXUS_USER }}@vanti.co.uk
          EOF
      - working-directory: ./ui/playground
        run: yarn install
      - working-directory: ./ui/playground
        run: yarn build

      # Build the go playground app, and release it
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - uses: goreleaser/goreleaser-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: release --rm-dist
